# Generated by Django 2.0.1 on 2021-01-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=30),
        ),
    ]
