# Generated by Django 2.0.1 on 2021-01-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramManytoMany',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('performer', models.ManyToManyField(to='index.Performer')),
            ],
        ),
    ]
