# Generated by Django 2.0.1 on 2021-01-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210105_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=40),
        ),
    ]
